### ISSUE TITLE
Option to set interpreter to use

### ISSUE THREAD

**Issue by rossburton** [pypa/installer#107]
I'm looking at using installer to install wheels in our distribution.  At runtime `sys.executable` is a special python wrapper that we use, but we don't want to use that on the target as it doesn't exist.

I think adding a simple `--interpreter` option should be sufficient for this use-case to set the `interpreter` parameter on `SchemeDictionaryDestination`, leaving the default as `sys.executable`.

**Comment by pradyunsg** [comment]
`installer`'s CLI is designed to install the wheel, for the currently running Python.

I'm curious, what exactly is your usecase for you're modifying with `sys.executable` and having that not point to a regular Python executable? Also, what project is this?

**Comment by rossburton** [comment]
Yocto Project, we're cross-compiling.  We have a magic sysconfig which knows about target paths when asked and assuming that sys.executable is the target is a bad assumption to make.

The interpreter we want to use is a standard interpreter, it's just not the running one.

**Comment by pradyunsg** [comment]
Hmm... Okie! I'm inclined to suggest that you maintain a tiny Python script that behaves exactly like you want it to, using the installer API -- for now, at the very least.

There's some discussion of an `--interpreter` option that behaves differently from what you're asking for here in https://github.com/pypa/installer/issues/98#issuecomment-1042484169; and I'm wary of just adding this as a CLI-maps-directly-to-API approach since one of the things I want to avoid is redistributors inventing their own target schemes instead of explicitly using what the interpreter would.

**Comment by FFY00** [comment]
We would need to run the target interpreter to instrospect the install paths anyway, so if that would be viable, so should you running `installer` on that interpreter directly. As I pointed out in other issues, using the paths from the current interpreter and trying to modify them to fit what we would usually expect to be in an external target interpreter is a bad idea and will cause lots of headaches. So, as @pradyunsg suggests, I think you would be much better off maintaining your own little script that places the files in the locations you expect for your particular usage.

**Comment by rossburton** [comment]
Our "host" Python is of the same version as the target and knows about target paths, so it mostly does do the right thing.  It's literally just the interpreter which needs updating.

**Comment by rossburton** [comment]
I had a quick look at this. I don't understand how writing a custom wrapper to call the installer API will solve my problem, when it's the installer API writing the hashbangs in `scripts.py`.  Am I missing something?

**Comment by pradyunsg** [comment]
You can control the interpreter used for those shebangs using the interpreter argument in https://installer.readthedocs.io/en/stable/api/destinations/#installer.destinations.SchemeDictionaryDestination.__init__

See the example in https://installer.readthedocs.io/en/stable/ and replace the relevant pieces there (get the scheme dict from your sysconfig magic, have `interpreter` be for whatever you want, and include whatever metadata you want).

**Comment by pradyunsg** [comment]
I'm gonna mark this as something that we're not going to implement, since I do believe that your usecase is covered by the API.

I'll leave this open so that you can confirm this. To keep this bounded, if there's no responses here after a reasonable amount of time, I'll go ahead and close this out.
