### ISSUE TITLE
PyQt5_Qt5 5.15.2 fails to install: PyQt5_Qt5-5.15.2.dist-info/RECORD is not mentioned in RECORD

### ISSUE THREAD

**Issue by yodaldevoid** [pypa/installer#149]
The wheel file for `PyQt5_Qt5` version 5.15.2 on PyPi has a RECORD file that lists itself at a a path of `PyQt5_Qt5-5.15.2.dist-info\RECORD`. It is my understanding that 5d1bab41e8c98beffb65e2a3e088a7e8491e2e63 should have fixed this issue, but perhaps there are other places where the path is being handled as per [PEP376](https://peps.python.org/pep-0376/#record) instead of the [Core Metadata specs](https://packaging.python.org/en/latest/specifications/recording-installed-packages/#the-record-file).

Both `installer` 0.5.1 and the latest main branch were tested.

**Comment by pradyunsg** [comment]
Hi @yodaldevoid! Thanks for filing this.

I've marked this as a bug, but I'll note for posterity that I've note actually spent the time to dig into the details of what's happening here. :)

**Comment by yodaldevoid** [comment]
It looks like the changes made in 5d1bab4 only affects writing out RECORD files, but not parsing them as is the issue here.
