### ISSUE TITLE
prefix always ends with /local/ on ubuntu

### ISSUE THREAD

**Issue by nlgranger** [pypa/installer#176]
Inside an ubuntu:22.04 container, I have installed build, installer and virtualenv in the latest version using pip.
The prefix value is concatenated with /local/ 

Steps to reproduce:

```sh
docker run --rm -it ubuntu:22.04
apt update
apt install python3-pip git
pip install -U build installer virtualenv
git clone https://github.com/pypa/installer.git
cd installer/
python3 -m build --wheel
python3 -m installer dist/*.whl --destdir=sysroot --prefix=/someprefix
find sysroot/
```

**Comment by pradyunsg** [comment]
Nothing that we can do here. This is an issue with the Python that ships with Ubuntu and the way they've modified it that breaks things.

https://discuss.python.org/t/linux-distro-patches-to-sysconfig-are-changing-pip-install-prefix-outside-virtual-environments/18240

**Comment by nlgranger** [comment]
I thought installer wasn't affected because it runs inside a virtualenv. Thanks for the pointer.
