### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [pypa/installer#199]
Hello!

I may have found a security issue in latest version of `Installer`. Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by pradyunsg** [comment]
This project now has private vulnerability reporting enabled.

Please reach out via the mechanisms described in https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability#privately-reporting-a-security-vulnerability.
